<?php

namespace Config;

use Config\Services;

$routes = Services::routes();

$routes->GET('laudostecnicos', 'LaudosTecnicos::index', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->GET('laudostecnicos/laudos', 'Laudos::index', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->GET('laudostecnicos/laudos/context/(:segment)/(:num)', 'Laudos::context_tab/$1/$2', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/laudos/list_data/(:segment)/(:num)', 'Laudos::list_data/$1/$2', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/laudos/list_data', 'Laudos::list_data', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->GET('laudostecnicos/laudos/modal_form', 'Laudos::modal_form', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->GET('laudostecnicos/laudos/modal_form/(:num)', 'Laudos::modal_form/$1', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/laudos/modal_form', 'Laudos::modal_form', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/laudos/modal_form/(:num)', 'Laudos::modal_form/$1', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/laudos/save', 'Laudos::save', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->GET('laudostecnicos/laudos/view/(:num)', 'Laudos::view/$1', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->GET('laudostecnicos/laudos/document/(:num)', 'Laudos::document/$1/full', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->GET('laudostecnicos/laudos/document/(:num)/(:segment)', 'Laudos::document/$1/$2', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->GET('laudostecnicos/laudos/pdf/(:num)', 'Laudos::download_pdf/$1/full', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->GET('laudostecnicos/laudos/pdf/(:num)/(:segment)', 'Laudos::download_pdf/$1/$2', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->GET('laudostecnicos/laudos/public/(:num)/(:segment)', 'Laudos::public_view/$1/$2', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->GET('laudostecnicos/laudos/share/(:segment)', 'Laudos::share_view/$1', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->GET('laudostecnicos/laudos/share/(:segment)/download', 'Laudos::share_download/$1', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->GET('laudostecnicos/portal', 'Laudos::portal', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/portal/feedback', 'Laudos::portal_feedback', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->GET('laudostecnicos/laudos/share-modal/(:num)', 'Laudos::share_modal_form/$1', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/laudos/share/(:num)', 'Laudos::share_save/$1', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->GET('laudostecnicos/laudos/duplicate_modal_form/(:num)', 'Laudos::duplicate_modal_form/$1', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/laudos/duplicate', 'Laudos::duplicate', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/laudos/change_status/(:num)', 'Laudos::change_status/$1', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/laudos/delete', 'Laudos::delete', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->GET('laudostecnicos/tipos', 'Types::index', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/tipos/list_data', 'Types::list_data', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->GET('laudostecnicos/tipos/modal_form', 'Types::modal_form', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->GET('laudostecnicos/tipos/modal_form/(:num)', 'Types::modal_form/$1', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/tipos/modal_form', 'Types::modal_form', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/tipos/modal_form/(:num)', 'Types::modal_form/$1', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/tipos/save', 'Types::save', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/tipos/toggle_status/(:num)', 'Types::toggle_status/$1', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/tipos/delete', 'Types::delete', ['namespace' => 'LaudosTecnicos\\Controllers']);

$routes->GET('laudostecnicos/categorias', 'Categories::index', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/categorias/list_data', 'Categories::list_data', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->GET('laudostecnicos/categorias/modal_form', 'Categories::modal_form', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->GET('laudostecnicos/categorias/modal_form/(:num)', 'Categories::modal_form/$1', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/categorias/modal_form', 'Categories::modal_form', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/categorias/modal_form/(:num)', 'Categories::modal_form/$1', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/categorias/save', 'Categories::save', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/categorias/toggle_status/(:num)', 'Categories::toggle_status/$1', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/categorias/delete', 'Categories::delete', ['namespace' => 'LaudosTecnicos\\Controllers']);

$routes->GET('laudostecnicos/statuses', 'Statuses::index', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/statuses/list_data', 'Statuses::list_data', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->GET('laudostecnicos/statuses/modal_form', 'Statuses::modal_form', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->GET('laudostecnicos/statuses/modal_form/(:num)', 'Statuses::modal_form/$1', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/statuses/modal_form', 'Statuses::modal_form', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/statuses/modal_form/(:num)', 'Statuses::modal_form/$1', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/statuses/save', 'Statuses::save', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/statuses/toggle_status/(:num)', 'Statuses::toggle_status/$1', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/statuses/delete', 'Statuses::delete', ['namespace' => 'LaudosTecnicos\\Controllers']);

$routes->GET('laudostecnicos/transitions', 'Transitions::index', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/transitions/list_data', 'Transitions::list_data', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->GET('laudostecnicos/transitions/modal_form', 'Transitions::modal_form', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->GET('laudostecnicos/transitions/modal_form/(:num)', 'Transitions::modal_form/$1', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/transitions/modal_form', 'Transitions::modal_form', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/transitions/modal_form/(:num)', 'Transitions::modal_form/$1', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/transitions/save', 'Transitions::save', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/transitions/toggle_status/(:num)', 'Transitions::toggle_status/$1', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/transitions/delete', 'Transitions::delete', ['namespace' => 'LaudosTecnicos\\Controllers']);

$routes->GET('laudostecnicos/historico-status', 'StatusHistory::index', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/historico-status/list_data', 'StatusHistory::list_data', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->GET('laudostecnicos/templates', 'Templates::index', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/templates/list_data', 'Templates::list_data', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->GET('laudostecnicos/templates/modal_form', 'Templates::modal_form', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->GET('laudostecnicos/templates/modal_form/(:num)', 'Templates::modal_form/$1', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/templates/modal_form', 'Templates::modal_form', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/templates/modal_form/(:num)', 'Templates::modal_form/$1', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/templates/save', 'Templates::save', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/templates/new_version', 'Templates::new_version', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->GET('laudostecnicos/templates/preview/(:num)', 'Templates::preview/$1', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/templates/publish/(:num)', 'Templates::publish/$1', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/templates/archive/(:num)', 'Templates::archive/$1', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/templates/toggle_status/(:num)', 'Templates::toggle_status/$1', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/templates/delete', 'Templates::delete', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->GET('laudostecnicos/checklists', 'Checklists::index', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/checklists/list_data', 'Checklists::list_data', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->GET('laudostecnicos/checklists/modal_form', 'Checklists::modal_form', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->GET('laudostecnicos/checklists/modal_form/(:num)', 'Checklists::modal_form/$1', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/checklists/modal_form', 'Checklists::modal_form', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/checklists/modal_form/(:num)', 'Checklists::modal_form/$1', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/checklists/save', 'Checklists::save', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/checklists/duplicate', 'Checklists::duplicate', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/checklists/publish/(:num)', 'Checklists::publish/$1', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/checklists/archive/(:num)', 'Checklists::archive/$1', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/checklists/toggle_status/(:num)', 'Checklists::toggle_status/$1', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/checklists/delete', 'Checklists::delete', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->GET('laudostecnicos/checklists/export/(:num)', 'Checklists::export/$1', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/checklists/import', 'Checklists::import', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->GET('laudostecnicos/checklists/progress/(:num)', 'Checklists::progress/$1', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/checklists/save_responses', 'Checklists::save_responses', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->GET('laudostecnicos/tipos-medicao', 'MeasurementTypes::index', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/tipos-medicao/list_data', 'MeasurementTypes::list_data', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->GET('laudostecnicos/tipos-medicao/modal_form', 'MeasurementTypes::modal_form', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->GET('laudostecnicos/tipos-medicao/modal_form/(:num)', 'MeasurementTypes::modal_form/$1', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/tipos-medicao/modal_form', 'MeasurementTypes::modal_form', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/tipos-medicao/modal_form/(:num)', 'MeasurementTypes::modal_form/$1', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/tipos-medicao/save', 'MeasurementTypes::save', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/tipos-medicao/toggle_status/(:num)', 'MeasurementTypes::toggle_status/$1', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/tipos-medicao/delete', 'MeasurementTypes::delete', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->GET('laudostecnicos/medicoes', 'Measurements::index', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/medicoes/list_data', 'Measurements::list_data', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->GET('laudostecnicos/medicoes/modal_form', 'Measurements::modal_form', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->GET('laudostecnicos/medicoes/modal_form/(:num)', 'Measurements::modal_form/$1', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/medicoes/modal_form', 'Measurements::modal_form', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/medicoes/modal_form/(:num)', 'Measurements::modal_form/$1', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/medicoes/save', 'Measurements::save', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->GET('laudostecnicos/equipamentos', 'Equipments::index', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/equipamentos/list_data', 'Equipments::list_data', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->GET('laudostecnicos/equipamentos/modal_form', 'Equipments::modal_form', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->GET('laudostecnicos/equipamentos/modal_form/(:num)', 'Equipments::modal_form/$1', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/equipamentos/modal_form', 'Equipments::modal_form', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/equipamentos/modal_form/(:num)', 'Equipments::modal_form/$1', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/equipamentos/save', 'Equipments::save', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/equipamentos/toggle_status/(:num)', 'Equipments::toggle_status/$1', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/equipamentos/delete', 'Equipments::delete', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->GET('laudostecnicos/normas', 'Norms::index', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/normas/list_data', 'Norms::list_data', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->GET('laudostecnicos/normas/modal_form', 'Norms::modal_form', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->GET('laudostecnicos/normas/modal_form/(:num)', 'Norms::modal_form/$1', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/normas/modal_form', 'Norms::modal_form', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/normas/modal_form/(:num)', 'Norms::modal_form/$1', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/normas/save', 'Norms::save', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/normas/toggle_status/(:num)', 'Norms::toggle_status/$1', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/normas/delete', 'Norms::delete', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/normas/link', 'Norms::link', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->GET('laudostecnicos/inspecoes', 'Inspections::index', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/inspecoes/list_data', 'Inspections::list_data', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->GET('laudostecnicos/inspecoes/agenda', 'Inspections::agenda', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->GET('laudostecnicos/inspecoes/agenda_events', 'Inspections::agenda_events', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->GET('laudostecnicos/inspecoes/view/(:num)', 'Inspections::view/$1', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->GET('laudostecnicos/inspecoes/mobile/(:num)', 'Inspections::mobile/$1', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->GET('laudostecnicos/inspecoes/modal_form', 'Inspections::modal_form', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->GET('laudostecnicos/inspecoes/modal_form/(:num)', 'Inspections::modal_form/$1', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/inspecoes/modal_form', 'Inspections::modal_form', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/inspecoes/modal_form/(:num)', 'Inspections::modal_form/$1', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/inspecoes/save', 'Inspections::save', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/inspecoes/checkin/(:num)', 'Inspections::checkin/$1', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/inspecoes/checkout/(:num)', 'Inspections::checkout/$1', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/inspecoes/start/(:num)', 'Inspections::start/$1', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/inspecoes/pause/(:num)', 'Inspections::pause/$1', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/inspecoes/finish/(:num)', 'Inspections::finish/$1', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/inspecoes/improductive/(:num)', 'Inspections::improductive/$1', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/inspecoes/upload_photo', 'Inspections::upload_photo', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/inspecoes/set_cover', 'Inspections::set_cover', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/inspecoes/reorder_photos', 'Inspections::reorder_photos', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/inspecoes/delete_photo', 'Inspections::delete_photo', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->GET('laudostecnicos/inspecoes/validate_completion/(:num)', 'Inspections::validate_completion/$1', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/inspecoes/delete', 'Inspections::delete', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->GET('laudostecnicos/nao-conformidades', 'Nonconformities::index', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/nao-conformidades/list_data', 'Nonconformities::list_data', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/nao-conformidades/plans_list_data', 'Nonconformities::plans_list_data', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/nao-conformidades/matrix_list_data', 'Nonconformities::matrix_list_data', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->GET('laudostecnicos/nao-conformidades/modal_form', 'Nonconformities::modal_form', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->GET('laudostecnicos/nao-conformidades/modal_form/(:num)', 'Nonconformities::modal_form/$1', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/nao-conformidades/modal_form', 'Nonconformities::modal_form', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/nao-conformidades/modal_form/(:num)', 'Nonconformities::modal_form/$1', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->GET('laudostecnicos/nao-conformidades/plan_modal_form', 'Nonconformities::plan_modal_form', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->GET('laudostecnicos/nao-conformidades/plan_modal_form/(:num)', 'Nonconformities::plan_modal_form/$1', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/nao-conformidades/plan_modal_form', 'Nonconformities::plan_modal_form', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/nao-conformidades/plan_modal_form/(:num)', 'Nonconformities::plan_modal_form/$1', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->GET('laudostecnicos/nao-conformidades/matrix_modal_form', 'Nonconformities::matrix_modal_form', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->GET('laudostecnicos/nao-conformidades/matrix_modal_form/(:num)', 'Nonconformities::matrix_modal_form/$1', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/nao-conformidades/matrix_modal_form', 'Nonconformities::matrix_modal_form', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/nao-conformidades/matrix_modal_form/(:num)', 'Nonconformities::matrix_modal_form/$1', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/nao-conformidades/save', 'Nonconformities::save', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/nao-conformidades/save_plan', 'Nonconformities::save_plan', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/nao-conformidades/save_matrix', 'Nonconformities::save_matrix', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/nao-conformidades/create_task/(:num)', 'Nonconformities::create_task/$1', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/nao-conformidades/sync_task/(:num)', 'Nonconformities::sync_task/$1', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/nao-conformidades/validate/(:num)', 'Nonconformities::validate/$1', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/nao-conformidades/delete', 'Nonconformities::delete', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->GET('laudostecnicos/configuracoes', 'Settings::index', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/configuracoes/save', 'Settings::save', ['namespace' => 'LaudosTecnicos\\Controllers']);

$routes->GET('laudostecnicos/ia', 'Ai::index', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/ia/save_settings', 'Ai::save_settings', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/ia/save_prompt', 'Ai::save_prompt', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->POST('laudostecnicos/ia/generate', 'Ai::generate', ['namespace' => 'LaudosTecnicos\\Controllers']);

$routes->GET('laudostecnicos/relatorios', 'Reports::index', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->GET('laudostecnicos/relatorios/print/(:segment)', 'Reports::print_view/$1', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->GET('laudostecnicos/relatorios/pdf/(:segment)', 'Reports::pdf/$1', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->GET('laudostecnicos/relatorios/export-csv/(:segment)', 'Reports::export_csv/$1', ['namespace' => 'LaudosTecnicos\\Controllers']);
$routes->GET('laudostecnicos/relatorios/export-xls/(:segment)', 'Reports::export_xls/$1', ['namespace' => 'LaudosTecnicos\\Controllers']);

$routes->group('api/laudos/v1', ['namespace' => 'LaudosTecnicos\\Controllers'], function ($routes) {
    $routes->POST('auth/login', 'Api_v1::login');
    $routes->POST('auth/logout', 'Api_v1::logout');
    $routes->POST('auth/refresh', 'Api_v1::refresh');
    $routes->GET('auth/profile', 'Api_v1::profile');
    $routes->GET('auth/devices', 'Api_v1::devices');
    $routes->POST('auth/devices/revoke/(:num)', 'Api_v1::revoke_device/$1');

    $routes->GET('laudos', 'Api_v1::laudos');
    $routes->POST('laudos', 'Api_v1::laudos');
    $routes->GET('laudos/(:num)', 'Api_v1::laudo/$1');
    $routes->GET('laudos/(:num)/history', 'Api_v1::laudo_history/$1');
    $routes->GET('laudos/(:num)/status', 'Api_v1::laudo_status/$1');
    $routes->GET('laudos/(:num)/pending', 'Api_v1::laudo_pending/$1');

    $routes->GET('inspections', 'Api_v1::inspections');
    $routes->GET('inspections/(:num)', 'Api_v1::inspection/$1');
    $routes->GET('inspections/(:num)/package', 'Api_v1::inspection_package/$1');
    $routes->POST('inspections/(:num)/start', 'Api_v1::inspection_start/$1');
    $routes->POST('inspections/(:num)/pause', 'Api_v1::inspection_pause/$1');
    $routes->POST('inspections/(:num)/finish', 'Api_v1::inspection_finish/$1');
    $routes->POST('inspections/(:num)/checkin', 'Api_v1::inspection_checkin/$1');
    $routes->POST('inspections/(:num)/checkout', 'Api_v1::inspection_checkout/$1');
    $routes->POST('inspections/(:num)/improductive', 'Api_v1::inspection_improductive/$1');

    $routes->GET('checklists/(:num)/download', 'Api_v1::checklists_download/$1');
    $routes->POST('checklists/responses', 'Api_v1::checklists_responses');
    $routes->POST('checklists/batch', 'Api_v1::checklists_batch');
    $routes->GET('checklists/(:num)/progress', 'Api_v1::checklists_progress/$1');
    $routes->GET('checklists/(:num)/pending', 'Api_v1::checklists_pending/$1');

    $routes->GET('measurements', 'Api_v1::measurements');
    $routes->POST('measurements', 'Api_v1::measurement_create');
    $routes->POST('measurements/(:num)', 'Api_v1::measurement_update/$1');
    $routes->POST('measurements/(:num)/equipment', 'Api_v1::measurement_equipment/$1');
    $routes->POST('measurements/(:num)/photo', 'Api_v1::measurement_photo/$1');

    $routes->POST('uploads/photo', 'Api_v1::upload_photo');
    $routes->POST('uploads/photos', 'Api_v1::upload_photos');
    $routes->POST('uploads/file', 'Api_v1::upload_file');
    $routes->POST('uploads/signature', 'Api_v1::upload_signature');
    $routes->POST('uploads/(:num)', 'Api_v1::upload_update/$1');
    $routes->POST('uploads/delete/(:num)', 'Api_v1::upload_delete/$1');

    $routes->GET('nonconformities', 'Api_v1::nonconformities');
    $routes->POST('nonconformities', 'Api_v1::nonconformity_create');
    $routes->POST('nonconformities/(:num)', 'Api_v1::nonconformity_update/$1');
    $routes->POST('nonconformities/(:num)/classify', 'Api_v1::nonconformity_classify/$1');
    $routes->POST('nonconformities/(:num)/photo', 'Api_v1::nonconformity_photo/$1');
    $routes->POST('nonconformities/(:num)/correction', 'Api_v1::nonconformity_correction/$1');

    $routes->GET('sync/pull', 'Api_v1::sync_pull');
    $routes->POST('sync/push', 'Api_v1::sync_push');
    $routes->GET('sync/status', 'Api_v1::sync_status');
});
