/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PontoHistoricoRouteImport } from './routes/ponto-historico'
import { Route as PontoAjusteRouteImport } from './routes/ponto-ajuste'
import { Route as PontoRouteImport } from './routes/ponto'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PendenciasRouteImport } from './routes/pendencias'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LancarAtividadeRouteImport } from './routes/lancar-atividade'
import { Route as DespesasRouteImport } from './routes/despesas'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjetosIndexRouteImport } from './routes/projetos.index'
import { Route as OrdensServicoIndexRouteImport } from './routes/ordens-servico.index'
import { Route as AvisosIndexRouteImport } from './routes/avisos.index'
import { Route as ProjetosIdRouteImport } from './routes/projetos.$id'
import { Route as OrdensServicoIdRouteImport } from './routes/ordens-servico.$id'
import { Route as AvisosIdRouteImport } from './routes/avisos.$id'
import { Route as ApiSplatRouteImport } from './routes/api.$'

const PontoHistoricoRoute = PontoHistoricoRouteImport.update({
  id: '/ponto-historico',
  path: '/ponto-historico',
  getParentRoute: () => rootRouteImport,
} as any)
const PontoAjusteRoute = PontoAjusteRouteImport.update({
  id: '/ponto-ajuste',
  path: '/ponto-ajuste',
  getParentRoute: () => rootRouteImport,
} as any)
const PontoRoute = PontoRouteImport.update({
  id: '/ponto',
  path: '/ponto',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PendenciasRoute = PendenciasRouteImport.update({
  id: '/pendencias',
  path: '/pendencias',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LancarAtividadeRoute = LancarAtividadeRouteImport.update({
  id: '/lancar-atividade',
  path: '/lancar-atividade',
  getParentRoute: () => rootRouteImport,
} as any)
const DespesasRoute = DespesasRouteImport.update({
  id: '/despesas',
  path: '/despesas',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosIndexRoute = ProjetosIndexRouteImport.update({
  id: '/projetos/',
  path: '/projetos/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdensServicoIndexRoute = OrdensServicoIndexRouteImport.update({
  id: '/ordens-servico/',
  path: '/ordens-servico/',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisosIndexRoute = AvisosIndexRouteImport.update({
  id: '/avisos/',
  path: '/avisos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosIdRoute = ProjetosIdRouteImport.update({
  id: '/projetos/$id',
  path: '/projetos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdensServicoIdRoute = OrdensServicoIdRouteImport.update({
  id: '/ordens-servico/$id',
  path: '/ordens-servico/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisosIdRoute = AvisosIdRouteImport.update({
  id: '/avisos/$id',
  path: '/avisos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/despesas': typeof DespesasRoute
  '/lancar-atividade': typeof LancarAtividadeRoute
  '/login': typeof LoginRoute
  '/pendencias': typeof PendenciasRoute
  '/perfil': typeof PerfilRoute
  '/ponto': typeof PontoRoute
  '/ponto-ajuste': typeof PontoAjusteRoute
  '/ponto-historico': typeof PontoHistoricoRoute
  '/api/$': typeof ApiSplatRoute
  '/avisos/$id': typeof AvisosIdRoute
  '/ordens-servico/$id': typeof OrdensServicoIdRoute
  '/projetos/$id': typeof ProjetosIdRoute
  '/avisos/': typeof AvisosIndexRoute
  '/ordens-servico/': typeof OrdensServicoIndexRoute
  '/projetos/': typeof ProjetosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/despesas': typeof DespesasRoute
  '/lancar-atividade': typeof LancarAtividadeRoute
  '/login': typeof LoginRoute
  '/pendencias': typeof PendenciasRoute
  '/perfil': typeof PerfilRoute
  '/ponto': typeof PontoRoute
  '/ponto-ajuste': typeof PontoAjusteRoute
  '/ponto-historico': typeof PontoHistoricoRoute
  '/api/$': typeof ApiSplatRoute
  '/avisos/$id': typeof AvisosIdRoute
  '/ordens-servico/$id': typeof OrdensServicoIdRoute
  '/projetos/$id': typeof ProjetosIdRoute
  '/avisos': typeof AvisosIndexRoute
  '/ordens-servico': typeof OrdensServicoIndexRoute
  '/projetos': typeof ProjetosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/despesas': typeof DespesasRoute
  '/lancar-atividade': typeof LancarAtividadeRoute
  '/login': typeof LoginRoute
  '/pendencias': typeof PendenciasRoute
  '/perfil': typeof PerfilRoute
  '/ponto': typeof PontoRoute
  '/ponto-ajuste': typeof PontoAjusteRoute
  '/ponto-historico': typeof PontoHistoricoRoute
  '/api/$': typeof ApiSplatRoute
  '/avisos/$id': typeof AvisosIdRoute
  '/ordens-servico/$id': typeof OrdensServicoIdRoute
  '/projetos/$id': typeof ProjetosIdRoute
  '/avisos/': typeof AvisosIndexRoute
  '/ordens-servico/': typeof OrdensServicoIndexRoute
  '/projetos/': typeof ProjetosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/despesas'
    | '/lancar-atividade'
    | '/login'
    | '/pendencias'
    | '/perfil'
    | '/ponto'
    | '/ponto-ajuste'
    | '/ponto-historico'
    | '/api/$'
    | '/avisos/$id'
    | '/ordens-servico/$id'
    | '/projetos/$id'
    | '/avisos/'
    | '/ordens-servico/'
    | '/projetos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/despesas'
    | '/lancar-atividade'
    | '/login'
    | '/pendencias'
    | '/perfil'
    | '/ponto'
    | '/ponto-ajuste'
    | '/ponto-historico'
    | '/api/$'
    | '/avisos/$id'
    | '/ordens-servico/$id'
    | '/projetos/$id'
    | '/avisos'
    | '/ordens-servico'
    | '/projetos'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/despesas'
    | '/lancar-atividade'
    | '/login'
    | '/pendencias'
    | '/perfil'
    | '/ponto'
    | '/ponto-ajuste'
    | '/ponto-historico'
    | '/api/$'
    | '/avisos/$id'
    | '/ordens-servico/$id'
    | '/projetos/$id'
    | '/avisos/'
    | '/ordens-servico/'
    | '/projetos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  DespesasRoute: typeof DespesasRoute
  LancarAtividadeRoute: typeof LancarAtividadeRoute
  LoginRoute: typeof LoginRoute
  PendenciasRoute: typeof PendenciasRoute
  PerfilRoute: typeof PerfilRoute
  PontoRoute: typeof PontoRoute
  PontoAjusteRoute: typeof PontoAjusteRoute
  PontoHistoricoRoute: typeof PontoHistoricoRoute
  ApiSplatRoute: typeof ApiSplatRoute
  AvisosIdRoute: typeof AvisosIdRoute
  OrdensServicoIdRoute: typeof OrdensServicoIdRoute
  ProjetosIdRoute: typeof ProjetosIdRoute
  AvisosIndexRoute: typeof AvisosIndexRoute
  OrdensServicoIndexRoute: typeof OrdensServicoIndexRoute
  ProjetosIndexRoute: typeof ProjetosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ponto-historico': {
      id: '/ponto-historico'
      path: '/ponto-historico'
      fullPath: '/ponto-historico'
      preLoaderRoute: typeof PontoHistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ponto-ajuste': {
      id: '/ponto-ajuste'
      path: '/ponto-ajuste'
      fullPath: '/ponto-ajuste'
      preLoaderRoute: typeof PontoAjusteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ponto': {
      id: '/ponto'
      path: '/ponto'
      fullPath: '/ponto'
      preLoaderRoute: typeof PontoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pendencias': {
      id: '/pendencias'
      path: '/pendencias'
      fullPath: '/pendencias'
      preLoaderRoute: typeof PendenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lancar-atividade': {
      id: '/lancar-atividade'
      path: '/lancar-atividade'
      fullPath: '/lancar-atividade'
      preLoaderRoute: typeof LancarAtividadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/despesas': {
      id: '/despesas'
      path: '/despesas'
      fullPath: '/despesas'
      preLoaderRoute: typeof DespesasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/': {
      id: '/projetos/'
      path: '/projetos'
      fullPath: '/projetos/'
      preLoaderRoute: typeof ProjetosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ordens-servico/': {
      id: '/ordens-servico/'
      path: '/ordens-servico'
      fullPath: '/ordens-servico/'
      preLoaderRoute: typeof OrdensServicoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avisos/': {
      id: '/avisos/'
      path: '/avisos'
      fullPath: '/avisos/'
      preLoaderRoute: typeof AvisosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/$id': {
      id: '/projetos/$id'
      path: '/projetos/$id'
      fullPath: '/projetos/$id'
      preLoaderRoute: typeof ProjetosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ordens-servico/$id': {
      id: '/ordens-servico/$id'
      path: '/ordens-servico/$id'
      fullPath: '/ordens-servico/$id'
      preLoaderRoute: typeof OrdensServicoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avisos/$id': {
      id: '/avisos/$id'
      path: '/avisos/$id'
      fullPath: '/avisos/$id'
      preLoaderRoute: typeof AvisosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  DespesasRoute: DespesasRoute,
  LancarAtividadeRoute: LancarAtividadeRoute,
  LoginRoute: LoginRoute,
  PendenciasRoute: PendenciasRoute,
  PerfilRoute: PerfilRoute,
  PontoRoute: PontoRoute,
  PontoAjusteRoute: PontoAjusteRoute,
  PontoHistoricoRoute: PontoHistoricoRoute,
  ApiSplatRoute: ApiSplatRoute,
  AvisosIdRoute: AvisosIdRoute,
  OrdensServicoIdRoute: OrdensServicoIdRoute,
  ProjetosIdRoute: ProjetosIdRoute,
  AvisosIndexRoute: AvisosIndexRoute,
  OrdensServicoIndexRoute: OrdensServicoIndexRoute,
  ProjetosIndexRoute: ProjetosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
