<?php echo form_open(get_uri('engenharia/laudos/save'), array('id' => 'engenharia-laudo-form', 'class' => 'general-form', 'role' => 'form')); ?>
<div class="modal-body clearfix"><input type="hidden" name="id" value="<?php echo esc($model_info->id); ?>" /><div class="container-fluid">
<?php $selects = array('client_id' => array('client', $clients_dropdown, true), 'contact_id' => array('engenharia_contact', $contacts_dropdown, false), 'project_id' => array('project', $projects_dropdown, false), 'type_id' => array('engenharia_type', $types_dropdown, true), 'technical_responsible_id' => array('engenharia_responsible', $team_members_dropdown, false), 'inspection_technician_id' => array('engenharia_inspection_technician', $team_members_dropdown, false), 'checklist_id' => array('engenharia_checklist', $checklists_dropdown, false)); foreach ($selects as $field => $config) { ?><div class="form-group"><div class="row"><label for="<?php echo $field; ?>" class="col-md-3"><?php echo $config[2] ? '* ' : ''; ?><?php echo app_lang($config[0]); ?></label><div class="col-md-9"><select id="<?php echo $field; ?>" name="<?php echo $field; ?>" class="select2 validate-hidden" <?php echo $config[2] ? 'data-rule-required="true"' : ''; ?>><?php foreach ($config[1] as $id => $label) { ?><option value="<?php echo esc($id); ?>" <?php echo ((string) $model_info->{$field} === (string) $id) ? 'selected' : ''; ?>><?php echo esc($label); ?></option><?php } ?></select></div></div></div><?php } ?>
<?php $text_fields = array('title' => array('title', true), 'inspection_address' => array('engenharia_inspection_address', false)); foreach ($text_fields as $field => $config) { ?><div class="form-group"><div class="row"><label for="<?php echo $field; ?>" class="col-md-3"><?php echo $config[1] ? '* ' : ''; ?><?php echo app_lang($config[0]); ?></label><div class="col-md-9"><input id="<?php echo $field; ?>" name="<?php echo $field; ?>" type="text" value="<?php echo esc($model_info->{$field}); ?>" class="form-control" <?php echo $config[1] ? 'data-rule-required="true"' : ''; ?> /></div></div></div><?php } ?>
<?php foreach (array('scheduled_date' => 'engenharia_scheduled_date', 'validity_date' => 'engenharia_validity') as $field => $label) { ?><div class="form-group"><div class="row"><label for="<?php echo $field; ?>" class="col-md-3"><?php echo app_lang($label); ?></label><div class="col-md-9"><input id="<?php echo $field; ?>" name="<?php echo $field; ?>" type="date" value="<?php echo esc($model_info->{$field}); ?>" class="form-control" /></div></div></div><?php } ?>
<?php foreach (array('objective' => 'engenharia_objective', 'scope' => 'engenharia_scope', 'installation_description' => 'engenharia_installation_description', 'internal_notes' => 'engenharia_internal_notes') as $field => $label) { ?><div class="form-group"><div class="row"><label for="<?php echo $field; ?>" class="col-md-3"><?php echo app_lang($label); ?></label><div class="col-md-9"><textarea id="<?php echo $field; ?>" name="<?php echo $field; ?>" class="form-control" rows="3"><?php echo esc($model_info->{$field}); ?></textarea></div></div></div><?php } ?>
</div></div><div class="modal-footer"><button type="button" class="btn btn-default" data-bs-dismiss="modal"><?php echo app_lang('close'); ?></button><button type="submit" class="btn btn-primary"><i data-feather="check-circle" class="icon-16"></i> <?php echo app_lang('save'); ?></button></div>
<?php echo form_close(); ?>
<script type="text/javascript">
$(document).ready(function () { $("#engenharia-laudo-form .select2").select2(); $("#engenharia-laudo-form").appForm({onSuccess: function () { if ($("#engenharia-laudos-table").length) { $("#engenharia-laudos-table").appTable({reload: true}); } else { window.location.reload(); } }}); function loadOptions(url, data, selector) { $.post(url, data, function (options) { var el = $(selector); el.empty(); $.each(options, function (id, text) { el.append($('<option>', {value: id, text: text})); }); el.trigger('change'); }, 'json'); } $("#client_id").on('change', function () { loadOptions('<?php echo_uri('engenharia/laudos/get_contacts'); ?>', {client_id: $(this).val()}, '#contact_id'); loadOptions('<?php echo_uri('engenharia/laudos/get_projects'); ?>', {client_id: $(this).val()}, '#project_id'); }); $("#type_id").on('change', function () { loadOptions('<?php echo_uri('engenharia/laudos/get_checklists'); ?>', {type_id: $(this).val()}, '#checklist_id'); }); });
</script>
